# Generated by Django 3.2.9 on 2021-12-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('specifications', '0002_auto_20211202_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='photos/product')),
                ('image_2', models.FileField(upload_to='photos/product')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='photos/product')),
                ('image_4', models.FileField(blank=True, null=True, upload_to='photos/product')),
                ('description', models.TextField(max_length=500)),
                ('is_available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specifications.specification')),
            ],
        ),
    ]
