# Generated by Django 3.2.9 on 2021-12-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
