# Generated by Django 3.2.9 on 2021-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.FileField(default=1, upload_to='photos/product'),
            preserve_default=False,
        ),
    ]
