# Generated by Django 3.2.9 on 2021-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='photos/product'),
        ),
    ]
