# Generated by Django 3.2.9 on 2021-12-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
        ('product', '0008_auto_20211202_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specifications.specification'),
        ),
    ]
