# Generated by Django 3.2.9 on 2021-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='country',
            field=models.CharField(blank=True, choices=[('Uzbekistan', 'uzbekistan'), ('Russia', 'russia'), ('Ukraine', 'ukraine'), ('Spain', 'spain'), ('Italy', 'italy'), ('Kazakhstan', 'kazakhstan'), ('Belorussia', 'belorussia')], max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
