# Generated by Django 3.2.9 on 2021-12-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20211203_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
