# Generated by Django 3.2.9 on 2021-12-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20211204_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='password_repeat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
