# Generated by Django 3.2.9 on 2021-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='delivery_country',
            field=models.CharField(choices=[('Alaska', 'alaska'), ('Hawaii', 'Hawaii'), ('California', 'California'), ('Nevada', 'Nevada'), ('Oregon', 'Oregon'), ('Washington', 'Washington'), ('Colorado', 'Colorado'), ('Idaho', 'Idaho'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('New', 'New'), ('Wyoming', 'Wyoming'), ('Arkansas', 'Arkansas'), ('Illinois', 'Illinois'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Fargona', 'Yassaviy kocha')], max_length=100),
        ),
    ]
